name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: 환경변수 설정
        run: echo "${{ secrets.MY_APPLICATION_YML}}" > ./src/main/resources/application.properties
        working-directory: ./server/linode/github-action-test

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: Copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: false # 오류로 중단하지 않도록 설정
          script: |
            # 1. 패키지 충돌 방지 및 시스템 업데이트
            echo "Updating system packages..."
            sudo yum update --skip-broken -y || true

            # 2. Java 설치
            echo "Installing Java..."
            sudo yum install -y java-17-amazon-corretto || true

            # 3. 충돌하는 패키지 처리 (필요 시 dracut-config-ec2 제거)
            echo "Checking for problematic packages..."
            if rpm -q dracut-config-ec2; then
              sudo yum remove -y dracut-config-ec2 || true
            fi

            # 4. 기존 Java 프로세스 종료
            echo "Terminating existing Java processes..."
            pgrep -f 'java -jar' | while read pid; do
              echo "Terminating Java process with PID: $pid"
              kill -9 $pid || true
            done

            # 5. 새로운 Java 프로세스 실행
            echo "Starting new Java process with nohup..."
            nohup java -jar ~/*.jar > ~/app.log 2>&1 &